name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy using ssh
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
            # Memeriksa apakah direktori ada
            if [ -d "/var/www/backendKoperasi" ]; then
              cd /var/www/backendKoperasi
              git pull origin main
              git status
              npm install --only=dev
            else
              echo "Direktori tidak ditemukan: /home/sangga/var/www/backendKoperasi"
              exit 1
            fi
          '
